/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.mortbay.ijetty;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int jicon=0x7f020001;
    }
    public static final class id {
        public static final int start=0x7f050000;
        public static final int stop=0x7f050001;
    }
    public static final class layout {
        public static final int jetty_controller=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int jetty_controller=0x7f040004;
        public static final int jetty_started=0x7f040001;
        public static final int jetty_stopped=0x7f040002;
        public static final int manage_jetty=0x7f040003;
        public static final int start_jetty=0x7f040005;
        public static final int stop_jetty=0x7f040006;
    }
}
